Linaro/meta-ledge

meta-ledge-sw/recipes-samples/images/ledge-gateway.bb

images: add ostree executables on ledge-gateway image

---

meta-ledge-bsp/conf/machine/ledge-espressobin.conf
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

Add config files for marvell espressobin

bsp: Add espressobin board

---

meta-ledge-bsp/conf/layer.conf
meta-ledge-bsp/conf/machine/ledge-espressobin.conf
meta-ledge-bsp/recipes-connectivity/hummingboard-btattach/hummingboard-btattach.bb
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_4.14.bb
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_4.17.bb
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
meta-ledge-sw/conf/layer.conf
meta-ledge-sw/recipes-connectivity/openavnu/openavnu-daemons_git.bb
meta-ledge-sw/recipes-security/optee/optee-test_git.bbappend

- Add compatibility flag
- Clean-up of recipes
- OPTEE-test: support of arm32 compilation
- OPENAVNU: correct git submodule issue

Thud support

---

meta-ledge-sw/recipes-samples/images/ledge-gateway.bb
meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-containers.bb
meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-python3.bb

Add python3 and containers (runc and docker)

Thud containers

---

meta-ledge-bsp/conf/machine/ledge-qemux86-64.conf
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

added x86_64 qemu machine. Checked with command bellow that image builds.
DISTRO=rpb MACHINE=ledge-qemux86-64 source ./setup-environment
bitbake   ledge-gateway

add ledge-qemux86-64 machine

---

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

add ledge-qemuarm64 machine

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

machine: add qemu arm7a support

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

Correctly define package list with comments and terminating \
Fixes: (43947684f1d41f4088J46e114f2287102efbe5ec6 implement packagegroup-ledge-iot.bb)

images: fix compilation for ledge-iot

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

Add cloud-init package on the ledge-iot image

images: add cloud-init on ledge-iot image

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

iot: add pam

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

images: ledge-iot add runc-docker

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

images: ledge-iot add iproute2

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

images: ledge-iot add gnupg2

---

meta-ledge-sw/conf/layer.conf
meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

- Align package name with OE name
- add description for several packages on comment

LEDGE-IOT: align with OE name

---

meta-ledge-sw/conf/layer.conf

CONF: add preferred version for efivar

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

KERNEL: correct issue with thud for reproducible build

---

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf
meta-ledge-bsp/recipes-ledge/images/ledge-image-bootfs.bb

- add bootfs image generation
- force format for bootfs images

Correction for raw creation

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/conf/machine/ledge-qemux86-64.conf

images: add 20GB space for all qemu builds

---

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf

ledge-ti-am572x: build raw ext4 image needed for ci

---

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf

for ti board we also need to add extra space to package
all our apps.

ledge-ti: add extra space

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

make ledge kernel number match rootfs number

---

meta-ledge-bsp/classes/image_types-ledge-raw.bbclass
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-basic.fld.template
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-basic.tsv.template
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.fld.template
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.tsv.template

The images as managed as variable on the flash layout and fiil during the image complete.

Management of flashlayout for stm32mp157c-dk2

---

meta-ledge-bsp/classes/image_types-ledge-raw.bbclass

FLASHLAYOUT: add correct extension for rootfs

---

meta-ledge-bsp/classes/image_types-ledge-raw.bbclass
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

Some change to help debian raw image generations

Proposation for debian raw generation

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.tsv.template
meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

Add support of tsv file for debian and modify script to adapt the name of rootfs on tsv file

Add support of tsv file for debian

---

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf
meta-ledge-sw/recipes-samples/images/ledge-gateway-lava.bb
meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-tpm-lava.bb

IMAGE: add package group for tpm and dependencies

---

meta-ledge-sw/recipes-samples/images/ledge-minimal.bb

place kernel image and modules inside image

---

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb

arm64: add uboot

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/wic/ledge-kernel-uefi.wks.in

ledge-qemu: arm, arm64: add wic images

---

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware-ledge_git.bb
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm64_defconfig

1. add atf for build
2.  uboot branch was rebased, so change git sha and turn on secure options. (Jira instructions).

qemuarm64: atf + secure uboot

---

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf

qemu: arm64: add optee-os in packages

---

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge-stm32mp157c-dk2/ledge_stm32mp157c_dk2_basic_defconfig
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge-stm32mp157c-dk2/ledge_stm32mp157c_dk2_trusted_defconfig
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.tsv.template
meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh
meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc

U-boot: use PARTLABEL on command line instead of device name
Kernel: rename modules tarball to be unique with specific link(not a link)
Raw-script: manage to generate bootfs with vfat format
Flashlayout: align flashlayout with script change

Management of debian purpose

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware-ledge_git.bb
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm_defconfig

just port ledge-qemuarm64 changes to ledge-qemuarm.

qemuarm: add secure uboot and tfa

---

meta-ledge-bsp/recipes-bsp/qemudtb/qemudtb-ledge-qemu.bb

to modify original dtb for qemu we need to generate it with the
same options which we use in run.

provide full cmd line for generated dtb

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

ledge-iot: Add podman on the list of packages

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware-ledge_git.bb
meta-ledge-bsp/recipes-bsp/qemudtb/qemudtb-ledge-qemu.bb
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm_defconfig
meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
meta-ledge-bsp/recipes-security/optee/optee-os_git.bbappend

stage one of patches. It hangs somewhere on transition to BL2 to BL3. After debugging will send correction patch.

ledge-qemuarm change to enable secure boot

---

meta-ledge-bsp/recipes-security/optee/optee-os_git.bbappend

OPTEE-OS: add space on append addons

---

meta-ledge-bsp/classes/tsv_fld_ledge.bbclass
meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc

- Kernel path issue for mkfs.ext4
- tsv: bashism issue on server

Several correction

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc

KERNEL: force dependency with e2fsprogs for mkfs.ext4

---

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf

bsp: ti: force am572x use LEDGE u-boot

---

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf

u-boot: ti: add UBOOT_MACHINE for ti board

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-uefi-keys-native.bb

missing original steps in .bb lacks of native dependancies,
instead of doing virtual do_deploy, move scenarios into
do do_install. Also add dependancy on built, packaged and placed
to image directory kernel before taking signature of it.

linux-ledge-uefi-keys: fix deps for uefi keys

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge/fragment-13-cmdline.config

kernel config turn on serial console for arm32

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/armv7a/FlashLayout_sdcard_armhf_without_boot_firmware.fld

FLASHLAYOUT: correct syntax of qemu

---

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge-stm32mp157c-dk2/ledge_stm32mp157c_dk2_basic_defconfig
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge-stm32mp157c-dk2/ledge_stm32mp157c_dk2_trusted_defconfig

U-Boot: add quiet on kernel command line

---

meta-ledge-bsp/classes/tsv_fld_ledge.bbclass
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.tsv.template

- remove line not take into account on tsv file
- add support of supported extension here wic.bin

FLASHLAYOUT: correct tsv not conform

---

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge.bb
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/0001-u-boot-ti-am572x-enable-boot_distrocmd.patch

U-Boot: TI: Enable distro_bootcmd command for am572x

---

meta-ledge-bsp/wic/ledge-ti-am572x.wks.in

image: Mark esp partition for am572x during wic creation

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc

KERNEL: export dtbs result on deploy dir

---

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf
meta-ledge-sw/recipes-samples/images/ledge-minimal.bb

The device tree directory are added via the kernel-devicetree package.

Add devicetree on boot directory of each ledge images

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

KERNEL: add management of renaming list of dtb

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/conf/machine/ledge-qemux86-64.conf
meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf
meta-ledge-bsp/conf/machine/ledge-synquacer.conf
meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf

wic: add dependancies between wic and initramfs generation

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf
meta-ledge-bsp/conf/machine/ledge-synquacer.conf
meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf

please do not merge until CI will pass.

do wic image creation after initramfs is prepared

---

meta-ledge-bsp/wic/ledge-stm32mp157c-dk2-optee.wks.in

wic: Fix initramfs path for ST board

---

meta-ledge-bsp/wic/ledge-stm32mp157c-dk2-optee.wks.in

WIC: stm32mp157c-dk2: fix size of bootfs

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/aarch64/FlashLayout_sdcard_arm64_without_boot_firmware.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/armv7a/FlashLayout_sdcard_armhf_without_boot_firmware.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh
meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc

- Support of device tree on tarball
- Support of initramfs

Update of raw script

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

RAW-SCRIPT: correct test issue

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/aarch64/FlashLayout_sdcard_arm64_without_boot_firmware.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/armv7a/FlashLayout_sdcard_armhf_without_boot_firmware.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

- Manage to put UUID on gtp partition
- Manage to use bootfs generated by OE if it's specified

RAW script

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/aarch64/FlashLayout_sdcard_arm64_without_boot_firmware.fld
meta-ledge-bsp/recipes-devtools/generate-raw-image/files/armv7a/FlashLayout_sdcard_armhf_without_boot_firmware.fld

Flashlayout: cleanup for debian purpose

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/ledge-flashlayout.bb

FLASHLAYOUT: correct shell syntax

---

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge_stm32mp157c_dk2_basic_defconfig
meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge_stm32mp157c_dk2_trusted_defconfig

stm: remove quite kernel parameter

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

RAW-SCRIPT: add exception when kernel are not here

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

RAW-SCRIPT: correct cross-case

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

RAW-SCRIPT: Fix bootfs name issue

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/armv7a/FlashLayout_sdcard_armhf_without_boot_firmware.fld

debian: use bootfs from multi platfrom

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-optee.bb

OPTEE-FTPM: re-enable optee-ftpm

---

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb

u-boot-ledge-qemu: update to new version of uefi patches

---

meta-ledge-bsp/conf/machine/include/ledge-qemu-common.inc

CONF: QEMU; decrease the size of EXTRA space to add on rootfs to 500MB

---

meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh

Mismatch on offset calcul between block of 1024 and 512

RAW-SCRIPT: correct fill issue

---

meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0001-STM32mp157c-dk2-optee-and-ethernet-support.patch
meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0002-ftpm.patch
meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0003-KERNEL-stm32mp157-dts-add-ftpm-support.patch
meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0004-optee-shm.patch
meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0005-op-tee-multi-page-shm.patch
meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0006-efi-libstub-Fix-kernel-command-line.patch
meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0007-ARM-dts-stm32-add-reboot-node-on-stm32mp157.patch
meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb

- Rework patch which generate warning when are applied
- add support of reboot for stm32mp157c-dk2

Kernel patch rework

---

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
meta-ledge-bsp/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware-ledge_git.bb

fip firmware image includes atf, optee and uboot.

compile atf fip image

---

meta-ledge-sw/recipes-security/optee/optee-ftpm.bb

Up to now we've been using a special port for fTPM, which was compiling
for Linux.
Microsoft has evolved it's fTPM since then and it can now be compiled
with OE. They also added support for OpenSSL.
Let's take one step at a time, switch to the upstream fTPM now. In the
future we can switch from the expliticitly defined WolfSSL to OpenSSL

ftpm: Use upstream packages

---

meta-ledge-sw/recipes-samples/images/ledge-gateway.bb
meta-ledge-sw/recipes-samples/images/ledge-iot.bb

Addition of efivar tools to manipulate efi variable.

IMAGE: add efivar tools

---

meta-ledge-sw/recipes-samples/images/ledge-iot.bb
meta-ledge-sw/recipes-security/parsec/cmake-native_%.bbappend
meta-ledge-sw/recipes-security/parsec/curl_%.bbappend
meta-ledge-sw/recipes-security/parsec/files/parsec.service
meta-ledge-sw/recipes-security/parsec/parsec_git.bb

First version to build and deploy Parsec without configure.

enable parsec app

---

meta-ledge-bsp/wic/ledge-kernel-uefi.wks.in

--part-nam="ESP" -> --part-name="ESP"

wic: fix parameter name

---

meta-ledge-bsp/recipes-bsp/edk2-efi-prebuild-fw/edk2-efi-prebuild-fw.bb

fix edk2 pflash creation after renaming

---

meta-ledge-sw/recipes-containers/podman/podman_git.bbappend

disable pseudo for podman build

---

meta-ledge-sw/recipes-containers/conmon/conmon_%.bbappend
meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

This reverts commit 85f2cd2d9eb272a2d198d2eda39c3123fea64bcd.
Now docker builds with with updating dependancies. Reverting this
commit.

re-enable podman

---

meta-ledge-sw/conf/layer.conf
meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
meta-ledge-sw/wic/ledge-kernel-uefi.wks.in

ledge-iot: add k3s

---

README.md

Signed-off-by: Peter Griffin <peter.griffin@linaro.org>

README.md: Add a bit of background info and xref with other projects

---

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb

Now that meta-ts has pkcs11 TA enabled, we can use this with pkcs11-tool. Tested with the following commands.
sudo pkcs11-tool --module /usr/lib/libckteec.so.0 --init-token --label testtoken --so-pin 12341234
Using slot 0 with a present token (0x0)
Token successfully initialized
sudo pkcs11-tool --module /usr/lib/libckteec.so.0 --label test-token --so-pin 12341234 --init-pin --pin 12341234
You can also test pkcs11 ta with Xtest
sudo xtest -t pkcs11
ledge-qemuarm64:~$ sudo xtest -t pkcs11
Run test suite with level=0
TEE test application started over default TEE instance
######################################################
#
#
######################################################
* pkcs11_1000 Initialize and close Cryptoki library
pkcs11_1000 OK
* pkcs11_1001 PKCS11: List PKCS#11 slots …

Add pkcs11-tool and mmc
