Linaro/meta-ledge

meta-ledge-bsp/conf/machine/ledge-espressobin.conf, meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
Remove machine files requirements from meta-marvell and add them directly
into our configuration
=> bsp: remove dependency on meta-marvell for espressobin

meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
=> bsp: Allow ledge-stm32mp157c-dk2 to use mainline kernel

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf
Add a default bootloader provider and configuration to perform a full build.
=> bsp: stm32mp157c-dk2: add default bootloader

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
OE supports command "runqemu <machine> nographic" make it work
for ledge-qemuarm i.e. "runqemu ledge-qemuarm nographic".
I.e. build and run sequence now is following:
DISTRO=rpb MACHINE=ledge-qemuarm source ./setup-environment
bitbake ledge-gateway
runqemu ledge-qemuarm nographic
( the latest command will run on x86 compiled kernel with rootfs under emulated arm virial machine.)
=> make ledge-qemuarm work

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf
There are larger patches in OE-core master branch to fix
the build issues with armv7ve tune flags, instead we are adding a
workaround for now based on this patch:
https://patchwork.openembedded.org/patch/151191/
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
=> ledge-stm32mp157c-dk2: workaround gcc-8 build issue with tune flags

meta-ledge-bsp/classes/image_types-ledge-raw.bbclass, meta-ledge-bsp/recipes-core/images/initramfs-ostree-image.bbappend, meta-ledge-bsp/recipes-ledge/images/ledge-image-bootfs.bb
The raw image MUST be created only for rootfs and not for other images.
=> correct issue for generation of raw image

meta-ledge-sw/recipes-connectivity/open62541/open62541_git.bb
Need to get top of branch for issue with gcc8.
=> OPEN62541: update to top of branch 0.3

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
grub is not compiling for armv7 yet
Since we don't have any real users let's remove it until it gets fixed
=> images: ledge-iot remove grub from package list

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
currently breaks the build with:
Initialising tasks...ERROR: Multiple .bb files are due to be built which each
provide pkgconfig:
Disable it until we choose a proper provider for the package
=> images: ledge-iot remove pkgconf

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
criu does not currently build for armv8 platforms. Let's remove it until
it's compilation is fixed
=> images: ledge-iot remove criu for armv8's

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge.bb
=> U-BOOT-LEDGE: stm32mp157c-dk2: add devicetree alignment with kernel 5.1

meta-ledge-sw/conf/layer.conf
Latest meta-rpb removes the fivar overlays for v0.30
Remove the custom 0.36 version from our local config and use whatever
oe-core offers
=> meta-ledge-sw: remove efivar custom versions

meta-ledge-sw/recipes-samples/images/ledge-iot.bb
coreutils is included in the iot packagegroup and the image file
=> images: ledge-iot remove duplicate coreutils entry

meta-ledge-sw/recipes-samples/images/ledge-iot.bb, meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
Since this is going for cloud deployements use the safer and better openSSH
instead of the dropbear implementation
=> images: ledge-iot replace dropbear with openssh

meta-ledge-bsp/conf/machine/ledge-qemux86-64.conf
Build for ledge-qemux86-64 will support ovmf files
compiled and efi linux boot support.
Run command needs to be extended for ovmf:
runqemu ledge-qemux86-64 nographic ovmf \
qemuparams="-m 4096" bootparams="selinux=0"
For quick test I see that kernel detects efifb:
[    0.000000] efi: EFI v2.60 by EDK II
[    0.000000] efi:  SMBIOS=0xbfe33000  ACPI=0xbfe5c000  ACPI 2.0=0xbfe5c014  MEMATTR=0xbf5e0698
[    2.108449] Registered efivars operations
[    2.620006] efifb: probing for efifb
[    2.620572] efifb: framebuffer at 0xc0000000, using 1876k, total 1875k
[    2.620813] efifb: mode is 800x600x32, linelength=3200, pages=1
[    2.621022] efifb: scrolling: redraw
[    2.621245] efifb: Truecolor: size=8:8:8:8, shift=24:16:8:0
=> ledge-qemux86-64: enable ovmf build

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf
This reverts commit 373cb7a3aacb040795ef3d5f9c366716b149d98d.
No need for extra space. Other deploy scripts can increase
size if needed.
=> Revert "ledge-ti: add extra space"

meta-ledge-bsp/classes/image_types-ledge-raw.bbclass, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-basic.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.fld
With this tow commit, the name of image are set during the process of raw image generation by openembedded.
=> Generate Raw image for different image name

meta-ledge-bsp/conf/machine/ledge-synquacer.conf, meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
Since marvell is not a member and we are not maintaining the espressobin image,
use it as a basis to produce synquacer images
=> bsdp: machines: move espressobin image to synquacer

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc, meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
Do_configure, do_install_append, EFi management and
fragments can be communalise between several kernel recipes.
=> LINUX−LEDGE: communalise linux functionality

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
The default modules tarball's containts unstripped kernel modules
and we need to have a set of module stripped.
=> KERNEL: generate stripped kernel modules tarball

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
For generating modules tarball with stripped modules
the deploy function must be called after package function.
=> KERNEL: correct call dependency

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf, meta-ledge-sw/recipes-samples/images/ledge-iot-lava.bb, meta-ledge-sw/recipes-samples/images/ledge-iot.bb
IOT Image: 
- add lava image with dependencies for tpm test
- add tsn and optee support of iot image.
=> Add lava image for IOT

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc, meta-ledge-sw/conf/layer.conf
create symlink for kernel inside /boot/efi/boot/ and
place bootaa64.efi there. Also aarch64 uses Image instead
of zImage.
=> ledge: enable /boot/efi

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-basic.fld.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-basic.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.fld.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh, meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0001-STM32mp157c-dk2-optee-and-ethernet-support.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0002-ftpm.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0003-KERNEL-stm32mp157-dts-add-ftpm-support.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
Kernel: 
- bump to kernel 5.3
- deploy kernel and devicetree for debian purpose
Machine: 
- remove usage of bootfs
Flashlayout:
- update flashlayout for removing bootfs
Debian:
- update script to add kernel and devicetree on rootfs
-
=> Kernel update and update for debian purpose

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb
We need to specify branch name for correct u-boot builing
and add build to the image.
=> ledge-qemuarm64: fix building u-boot

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-basic.fld.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-basic.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.fld.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.tsv.template
Revert the two patch which originally remove usage of bootfs
=> Re-activate bootfs

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
cryptsetup  conflicts with cryptsetup-tpm-incubator,
removing it.
=> packagegroup-ledge-iot.bb: drop cryptsetup

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/fragment-13-cmdline.config, meta-ledge-bsp/wic/ledge-kernel-uefi.wks.in
place gpt table inside image and mark root partition with
label rootfs. Kernel mounts that partition with
root=PARTLABEL=rootfs option.
=> wic: use gpt label to mount rootfs

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
Boot partition should have only one linux kernel,
like /boot/efi/boot/bootaa64.efi. Because of vfat
does not support symlinks wic image builder just
duplicate files. Let's save some space and have
more clean filesystem.
=> wic: efi: install only one copy of the kernel

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
=> recipes-kernel: fix _APPEND typo

meta-ledge-sw/conf/layer.conf, meta-ledge-sw/recipes-samples/images/ledge-iot.bb, meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb, meta-ledge-sw/recipes-samples/packagegroups/packagegroup-security-tpm2.bbappend
1. meta-securuty in zeus has more priority then meta-ledge. Fixing it.
2. cryptsetup-tpm-incubator should replace cyptsetup but it has lower
version number. Comment it out for now to make ledge-iot image build.
=> ledge: fix ledge-iot build with commenting out cryptsetup-tpm-incubator

meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0004-op-tee-shm.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0005-op-tee-multi-page-shm.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
A hack was needed for fTPM + QEMU as reported here
https://lkml.org/lkml/2019/7/3/60
Pick up patches that have not been applied to our current kernel
Signed-off-by: Ilias Apalodimas ilias.apalodimas@linaro.org
=> ledge: kernel: add patches for fTPM and shm usage

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware-ledge_git.bb, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb, meta-ledge-bsp/recipes-security/optee/optee-os_git.bbappend
- this commit does not fix runqemu script run, script  itself needs changes to support virtioblk for arm.
=> ledge-qemuarm64: add symlinks for secure boot

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm64_defconfig, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm_defconfig
U-boot grew in size with the TF-A and efidebug additions. Change the kernel
load address to account for that.
In addition use bootefi bootmgr and set BootOrderXXX variable correctly
since we move towards a full UEFI compliant boot.
=> qemu: change u-boot boot command

meta-ledge-bsp/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware-ledge_git.bb, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0004-op-tee-shm.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0005-op-tee-multi-page-shm.patch
Corectly add SPD=opteed in build options for TF-A in aarch64
=> tf-a: Fix aarch64 builds for OP-TEE

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/recipes-bsp/qemudtb/files/0001-qemuarm64.dts-add-ftpm-support.patch, meta-ledge-bsp/recipes-bsp/qemudtb/qemudtb-ledge-qemu.bb
qemu has dbt build in in qemu binary, which loads once qemu
boots. We need to add ftpm to that dtb.
=> ledge-armqemu64: add qemu dtb with ftpm

meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh
When the script are launched, the tools sgdisk and mkfs.vfat are not
found, force path to call the tools.
=> RAW-SCRIPT: force path for sgdisk and mkfs.vfat tools

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf, meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
save disk space and deploy only wic image.
=> qemu: do not install ext4 and tar rootfs

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm64_defconfig, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm_defconfig
Since the QEMU platforms will load PE/KEK/db/dbx from a virtio device,
until we implement secure storage in QEMU wee need a way of protecting
the UEFI variables.
Let's disable the u-boot env and set the bootdelay to 0
so the user can't change those for U-Boot's command line
=> qemu: u-boot: disable u-boot and and set delay to 0

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm64_defconfig
qemuparams="..." or QB_OPT_APPEND append option after first
rootfs.  So that virtio-0 is certs image and virtio-1 is
kernel and rootfs.
=> ledge-qemuarm64: run kernel with signed certificates

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf, meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware-ledge_git.bb, meta-ledge-bsp/recipes-bsp/qemudtb/qemudtb-ledge-qemu.bb, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu.bb, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm_defconfig, meta-ledge-bsp/recipes-security/optee/optee-os_git.bbappend
This patch make runqemu command run for ledge-qemuarm. Changes
touch cleanups in atf, uboot, optee and machine config files.
=> finally fix qemuarmv7 part 2

meta-ledge-bsp/classes/tsv_fld_ledge.bbclass
correct bashism issue on server:
run.tsv_fld_template_for_ledge.8521: 104: [: unexpected operator
=> TSV management: correct bashism

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm64_defconfig, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge-qemu/ledge-qemuarm_defconfig
without virtio scan block devices some time are not
discovered.
=> add virtio scan before loading kernel

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/aarch64/FlashLayout_sdcard_arm64_without_boot_firmware.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/armv7a/FlashLayout_sdcard_armhf_without_boot_firmware.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld
Due to upload script, the extension must be tgz instead of tar.gz
=> FLASHLAYOUT: correct wrong extension of kernel module

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf, meta-ledge-bsp/wic/ledge-ti-am572x.wks.in
Create a WIC image that contains three partitions.
First one is firmware + dtb. Use an external dtb for now since the
U-Boot embedded one is not up to date. Second partition has the kernel
only and the third one rootfs.
In order to boot the board with UEFI use:
setenv bootargs 'efi=novamap,noruntime console=ttyS2,115200 rootwait root=/dev/mmcblk0p3 selinux=0'
load mmc 0:1 $fdt_addr_r am572x-idk.dtb; load mmc 0:2 $kernel_addr_r efi/boot/bootarm.efi; bootefi $kernel_addr_r $fdt_addr_r
This will eventually be applied to TI u-boot config in a following patch
=> bsp: ti: Boot am572x with UEFI

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf, meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/conf/machine/ledge-qemux86-64.conf, meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc, meta-ledge-bsp/recipes-kernel/linux/linux-ledge-uefi-keys.bb, meta-ledge-bsp/wic/ledge-kernel-uefi.wks.in
This patch enables wic image for ledge-qemux86_64 and also makes
'runqemu ledge-qemux86-64 ovmf wic nographic' command works.
OVMF can be used upstream or from current build. Patch also depends
on upstream fix to OE.
=> enable wic image for qemu x86

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-uefi-keys-native.bb
use native host tools for sign and image generation.
(native = native tools which bitbake builds.)
=> fix paths for efi host tools

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-uefi-keys-native.bb
+= appends string without whitespace. That leads to
wrong dependancies matches. For some reason bitbake
does not warn on this but fails to build because of
sysroot is not populated with dependancies.
=> linux-ledge-uefi-keys-native: fix defining depends

meta-ledge-bsp/recipes-kernel/linux/linux-ledge/fragment-13-cmdline.config
by defaut serial conole is enabled for arm, arm64 but not
for x86. If we run qemu virtual machine we want to see
the same console.
Also turn on kernel built in command line.
=> kernel config: enable serial console

meta-ledge-bsp/wic/ledge-ti-am572x.wks.in
Since we upstreamed our changes on WIC and bootefi module, use that while
generating the TI board ESP partition
=> images: Change efi partition generation for ti am572x

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/fragment-15-cleanup.config
The qemu images are used as reference to be used on several hardware
and need to have all device tree for hardware supported.
=> CONF: force generation of devicetree during for qemu machine

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
=> KERNEL: put the result of dtbs on kernel-devicetree package

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
The goal for creating dtb directory are to have a something to put
kernel-devicetree package
=> KERNEL: force the creation of dtb directory

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/0001-u-boot-ti-am572x-enable-boot_distrocmd.patch
fdtfile needs to be undefined so distro_bootcmd searches for the proper
filename
=> ledge: uboot: remove fdtfile=undefined from the TI am572x board

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf, meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
Since we install the dtbs on the ESP partition remove it from the
firmware one
=> bsp: remove dtb from firmware partition on am572x

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc, meta-ledge-bsp/wic/ledge-ti-am572x.wks.in, meta-ledge-sw/recipes-samples/images/ledge-initramfs.bb
We need to provide a way for devices to mount our rootfs regardless of
the installation medium and partitions.
The currently used root=PARTUUID="uuid" is only working properly on
devices that support GPT. Although a pseudo uuid is generated for MBR,
we can't control it's value from WIC image generation tools and even if
we could, the generated uuid would differ from the GPT one.
Let's add filesystem UUID and an initramfs so we'll be able to mount root partitions
with root=UUID="uuid"
This patch only implements the initramfs generation and adds the proper
filesystem uuid to the WIC image for the TI board.
At the moment we add don't add kernel modules in the initramfs so the image is
2.7mb. This is expected to grow if we need modules in different devices
Signed-off-by: Ilias Apalodimas …
=> images: add initramfs image generation

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf, meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/conf/machine/ledge-qemux86-64.conf, meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf, meta-ledge-bsp/conf/machine/ledge-synquacer.conf, meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf, meta-ledge-bsp/recipes-kernel/linux/linux-ledge-common.inc
The INITRAMFS configuration MUST be associated to a machine.
=> CONF: Put initramfs configuration on machine

meta-ledge-bsp/classes/tsv_fld_ledge.bbclass
In case of initramfs image, don't need to change the tsv.
=> CLASS: TSV: make nothing for initramfs image

meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0006-efi-libstub-Fix-kernel-command-line.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge/fragment-13-cmdline.config, meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb, meta-ledge-bsp/wic/ledge-ti-am572x.wks.in, meta-ledge-sw/recipes-samples/images/ledge-initramfs.bb
Fix kernel parsing for initrd= from the default cmd-line and
add a CONFIG_CMDLINE with initramfs and UUID.
This will aloow our distro to boot regardless of the bootloader as long
as the partition uuid is set correctly
=> images: Use initramfs

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf, meta-ledge-bsp/wic/ledge-stm32mp157c-dk2-optee.wks.in
- modify wks file for initramfs usage
- add dependency for wic generation
=> CONF: stm32mp157c-dk2: adapt wks file for initramfs usage

meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0006-efi-libstub-Fix-kernel-command-line.patch
On the previous patch we didn't accept and extended commandline if
_EXTEND was not configured. Unfortunately the kernel treat
CONFIG_CMDLINE_* per architecture so EXTEND is not present on armv8.
Change the approach and only respect _FORCE arguemens, extend the
cmdline for other configurations
=> kernel: fix initrd parsing from kernel commandline

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf, meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/recipes-kernel/linux/linux-ledge-sign.inc
IMAGE_FS_TYPES_remove +="ext4" deletes all images with
ext4 extentions. We need to rename this image.
=> linux-ledge: change cert image extension name

meta-ledge-bsp/recipes-devtools/generate-raw-image/ledge-flashlayout.bb
bash ls can return error return code if there is no files
and trap bb execution.
=> ledge-flashlayout.bb: use find instead of bash ls

meta-ledge-bsp/recipes-kernel/linux/linux-ledge-sign.inc
Previously the ledge-kernel-uefi-certs.ext4.img file was create and
deployed directly to the tmp-rpb-glibc/deploy/image/*/ dir.
This means it is  not saved in sstate and won't be present in using sstate
on subsequent runs.
This change aligns more with std OE practice and allows sstate to work.
Signed-off-by: Bill Mills <wmills@ti.com>
=> fix sstate handling of cert ext4 image

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/0001-u-boot-ti-am572x-enable-boot_distrocmd.patch, meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
commit d2fdc3800d1a ("U-Boot: TI: Enable distro_bootcmd command for am572x")
commit 462d3f3fd30d ("KERNEL: add renaming list for dts")
We enabled 'run distro_bootcmd' for am572x-idk board.
This board has it's U-boot ${soc} variable set to 'omap5' and ${board}
to 'am57xx'. Since distro_bootcmd looks for an fdt named
${soc}-${board}.dtb we also introduced a renaming scheme while building
our kernels renaming am572x-idk.dtb -> omap5-am57xx.dtb.
It turns out the same image can run on X15 beagleboard, with a
different dtb. So instead of renaming the dtb, change the U-boot command
slightly and run 'findfdt' before booting 'distro_bootcmd' and support
both boards.
=> U-Boot: TI: Allow distro_bootcmd to boot more am572x based SoCs

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf
stm flasher uses ext4 rootfs image to create bootable
sd card.
=> keep ext4 images needed for stm flasher

meta-ledge-bsp/classes/tsv_fld_ledge.bbclass, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh
To manage the diversity of configuration, stm32mp157c-dk2, qemu, debian,
the flashlayout are simplify.
- stm32mp157-cdk2: use of ext4 image
- qemu: use of ext4 image
- debian: use of ext4 image
The wic are not more use because we are not able to know on which mode we are.
=> FLASHLAYOUT: manage diversity

meta-ledge-bsp/conf/machine/include/ledge-qemu-common.inc
We want to fit into most common sd card (8Gb or 16Gb).
=> add only 2Gb as empty space for ext4 images.

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf, meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
add -serial stdio to allow ctrl+c interrupt runqemu
script.
I.e.
runqemu ledg.qemuboot.conf wic - will trap on crtl+c
runqemu ledg.qemuboot.conf wic serial - will not trap on ctrl+c
and passes signal to virtual machine.
=> make crtl+c work with runqemu script

meta-ledge-bsp/recipes-devtools/generate-raw-image/files/aarch64/FlashLayout_sdcard_arm64_without_boot_firmware.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/armv7a/FlashLayout_sdcard_armhf_without_boot_firmware.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-qemuarm/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.tsv.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-debian.fld, meta-ledge-bsp/recipes-devtools/generate-raw-image/files/ledge-stm32mp157c-dk2/FlashLayout_sdcard_ledge-stm32mp157c-dk2-optee.fld.template, meta-ledge-bsp/recipes-devtools/generate-raw-image/raw-tools/create_raw_from_flashlayout.sh
Support of Partition type: gpt and dos. 
Add support of raw content (not associated to a partition.
Example with dos partition type:
PARTITION	DOS
#Opt: P=Populate, E=Empty R=Raw
#Type: Binary=raw partition, FileSystem=fs partition(ext4, fat)
#Ofsset on hexa
#Opt	Name	Type	Offset	Binary
R	fsbl1	Binary	0x00004400	arm-trusted-firmware/tf-a-stm32mp157c-dk2.stm32
R	fsbl2	Binary	0x00044400	arm-trusted-firmware/tf-a-stm32mp157c-dk2.stm32
P	bootfs	System	0x00344400	ledge-iot-ledge-stm32mp157c-dk2-20200310014126.bootfs.vfat
P	rootfs	FileSystem	0x04344400	ledge-iot-ledge-stm32mp157c-dk2-20200310014126.rootfs.ext4
=> Raw script: add support of partition type

meta-ledge-sw/recipes-extended/procps/procps_%.bbappend
disable audit messages on boot console.
=> sysctl: lower kernel verbosity on boot

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
ledge-synquacer uses tag.xz which is used on multi-platfrom
builds.
--
this has to fix synquacer lava job for multi platform builds.
=> qemuarm64: do not delete tar.xz image

meta-ledge-bsp/recipes-kernel/linux/linux-ledge/fragment-13-cmdline_x86.config
linux kernel before 5.7 does not support initrd passed
from UEFI. Use this patch as temporary solution to mount
rootfs by label.
=> ledge-qemu-x86: revert back mount rootfs from initrd

meta-ledge-sw/conf/layer.conf
partially revert:
872ea3e CONF: Use enforcing policy for selinux
For now selinux blocks reboot and shutdown for root user.
This commit reverts default selinux policy which to permissive
- i.e. generate warnings instead of block commands. For not it's
intended that admin have to update selinux rules for his
applications then switch selinux mode to enforcing (blocking mode).
=> revert: 872ea3e CONF: Use enforcing policy for selinux

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
systemd-analyze can be used to to get statistics
for system boot. Like:
~#systemd-analyze time
Startup finished in 11.999s (kernel) + 43.946s (userspace) = 55.946s
multi-user.target reached after 41.802s in userspace
=> ledge-iot: add systemd-analyze utility

meta-ledge-bsp/conf/machine/ledge-qemuarm.conf, meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf
we fix dtb in qemu binary, no need to pass it as command
line.
=> runqemu: fimware->firmware and do not pass dtb

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-iot.bb
chkconfig, python-setuptools - is not needed on target.
dnf - is package manager,  opkg is used for OE.
=> remove unbuildable packages for dunfell branch

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-tpm-lava.bb
remove unbildable package python-pyyaml from
dunfell branch.
=> remove python-pyyaml from lava images

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf
=> CONF:TI: use UBOOT_CONFIG instead of UBOOT_MACHINE

meta-ledge-bsp/conf/machine/ledge-stm32mp157c-dk2.conf, meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf, meta-ledge-bsp/recipes-bsp/trusted-firmware-a/trusted-firmware-a-ledge_git.bb, meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge.bb
The PROVIDES variables was set on bad location. The variable must be set after the include of u-boot.inc
=> Correct issue with u-boot provider

meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge.bb
stm target depens on virtual/bootloader on RDEPENDS,
but uboot.inc adds it only to DEPENDS. Define virtual
provider for RDEPENDS as well.
=> uboot: add virtual/bootloader

meta-ledge-bsp/recipes-security/optee/optee-os/0001-allow-setting-sysroot-for-libgcc-lookup.patch
The patch are updated to be compatible with optee-os 3.10, 
=> OPTEE-OS: adapt patch to 3.10.0

meta-ledge-bsp/recipes-bsp/edk2-efi-prebuild-fw/edk2-efi-prebuild-fw.bb, meta-ledge-bsp/recipes-bsp/trusted-firmware-a/trusted-firmware-a-ledge_git.bb
Use firmare images name as we agreed to be used by run
and CI scripts.
=> rename firmware images to common name

meta-ledge-bsp/conf/machine/ledge-qemux86-64.conf
=> ledge-qemux86-64: add edk2 fw to RRDPENDS and remove ovmf build

meta-ledge-bsp/recipes-bsp/edk2-efi-prebuild-fw/edk2-efi-prebuild-fw.bb
=> correct qemux86-64 machine name in x86 edk2 firmware

meta-ledge-bsp/conf/machine/ledge-qemuarm64.conf, meta-ledge-bsp/recipes-bsp/trusted-firmware-a/trusted-firmware-a-ledge_git.bb
use firmware.uefi.bin for pflash device.
=> ledge-qemuarm64: use firmware.uefi.bin for pflash

meta-ledge-sw/recipes-samples/packagegroups/packagegroup-ledge-optee.bb
commit b90bdec4ff95("U-BOOT: add patch for stm32mp157c-dk2")
accidentally removed fTPM compilation. Fix it
=> packages: reenable ftpm

meta-ledge-sw/recipes-security/optee/optee-ftpm.bb, meta-ledge-sw/recipes-security/optee/optee-ftpm/0000-fix-ssl-fallthrough.patch
Fix the attribute(fallthrough) issue caused by optee and wolfssl macros.
While at it update to the latest master branch
=> ftpm: Fix compilation and bump to latest

meta-ledge-bsp/recipes-bsp/edk2-efi-prebuild-fw/edk2-efi-prebuild-fw.bb
firmware.uefi.edk2.bin
firmware.uefi.uboot.bin
=> use common name for firmware (edk2 and uboot)

meta-ledge-bsp/recipes-devtools/pseudo/pseudo_git.bbappend, meta-ledge-sw/recipes-security/parsec/parsec_git.bb
podman needs updated pseudo tool to not fail.
=> update pseudo tool

meta-ledge-bsp/recipes-kernel/linux/linux-ledge_mainline.bb
Fix build under docker without insalled elfutils:
|   HOSTCC  scripts/bin2c
| error: Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y,
please install libelf-dev, libelf-devel or elfutils-libelf-devel
|   HOSTCC  scripts/kallsyms
p.s.
the same dep has yocto-linux.bb
=> linux-ledge: add elfutils-native deps

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf, meta-ledge-sw/recipes-samples/packagegroups/packagegroup-security-tpm2.bbappend
append is definately missing to extend security
package with parsec instead of redifine the list.
=> do not redefine packagegroup-security-tpm2

meta-ledge-bsp/conf/machine/ledge-ti-am572x.conf
Expression += adds wks file while if original from ti
was set ledge wks file was missing.
=> ledge-ti-am572x.conf: set wks file

meta-ledge-sw/recipes-containers/podman/podman_%.bbappend, meta-ledge-sw/recipes-containers/podman/podman_git.bbappend
3.2.1 includes fixes to install stage which caused podman failures.
=> update  podman

meta-ledge-sw/recipes-security/optee/optee-ftpm.bb, meta-ledge-sw/recipes-security/optee/optee-ledge.bb
With changes in meta-linaro:
https://review.linaro.org/c/openembedded/meta-linaro/+/39634
drop sysroot patch from meta-ledge.
=> optee-os: drop remove allow-setting-sysroot-for-libgcc-lookup.patch

meta-ledge-sw/recipes-multimedia/libcamera/libcamera.bbappend, meta-ledge-sw/recipes-multimedia/libcamera/libcamera/0001-ipa-rkisp1-Introduce-sensor-degamma.patch, meta-ledge-sw/recipes-multimedia/libcamera/libcamera/0001-uvcvideo-Use-auto-variable-to-avoid-range-loop-warni.patch, meta-ledge-sw/recipes-multimedia/libcamera/libcamera/0002-ipa-rkisp1-Use-frame-index.patch, meta-ledge-sw/recipes-multimedia/libcamera/libcamera/0003-ipa-rkisp1-Introduce-Black-Level-Correction.patch, meta-ledge-sw/recipes-multimedia/libcamera/libcamera/0004-ipa-rkisp1-Introduce-AWB.patch, meta-ledge-sw/recipes-multimedia/libcamera/libcamera/0005-ipa-rkisp1-Introduce-crosstalk-correction.patch, meta-ledge-sw/recipes-multimedia/libcamera/libcamera/0006-ipa-rkisp1-agc-Introduce-histogram-calculation.patch
Bumps SRCREV of libcamera for hardnott and updates meson build system options. This also enables libcamera pipelines for rpi, rockchip and uvcvideo. We also add rkisp1 ipa patches from the libcamera mailing list that increase the image quality of the images captured.
Tested on RockPi4b with Sony imx219.
Example image without 3a https://people.linaro.org/~peter.griffin/rkisp1captures/test_no3a.png
Example image with these patches applied https://people.linaro.org/~peter.griffin/rkisp1captures/test_3a.png
=> Hardknott libcamera SRCREV bump & Rockchip ipa improvements

meta-ledge-sw/recipes-4upstream/libcamera-apps/libcamera-apps.bb
libcamera-apps is a small suite of libcamera based applications.
Add a recipe to build it and put it here as a temp place until
we find somewhere to upstream it to.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> libcamera-apps.bb: Add a recipe for libcamera-apps

meta-ledge-sw/recipes-security/optee/optee-client/0001-libckteec-add-support-for-ECDH-derive.patch, meta-ledge-sw/recipes-security/optee/optee-client/0002-tee-supplicant-introduce-struct-tee_supplicant_param.patch, meta-ledge-sw/recipes-security/optee/optee-client/0003-tee-supplicant-refactor-argument-parsing-in-main.patch, meta-ledge-sw/recipes-security/optee/optee-client/0004-tee-supplicant-rpmb-introduce-readn-wrapper-to-the-r.patch, meta-ledge-sw/recipes-security/optee/optee-client/0005-tee-supplicant-rpmb-read-CID-in-one-go.patch, meta-ledge-sw/recipes-security/optee/optee-client/0006-tee-supplicant-add-rpmb-cid-command-line-option.patch, meta-ledge-sw/recipes-security/optee/optee-client_%.bbappend, meta-ledge-sw/recipes-security/optee/optee-os_%.bbappend, meta-ledge-sw/recipes-security/optee/optee-test_%.bbappend
My local rpmb dev_id +1 hack no longer works, as rpmb device jumps around from one boot to the next. So bump to v3.16 to match meta-ts and provide Jeromes patches to optee-client.
I also tested xtest -t pkcs11 and that now runs sucessfully.
=> bump optee to v3.16

meta-ledge-sw/recipes-containers/runc/runc-opencontainers_%.bbappend, meta-ledge-sw/recipes-extended/ostree/ostree_%.bbappend
The recipes:
- [meta-openembedded/]meta-oe/recipes-extended/ostree/ostree_2021.1.bb from
https://github.com/openembedded/meta-openembedded @ 9ee0e08ba239 and
- [meta-virtualization/]recipes-containers/runc/runc-opencontainers_git.bb
from http://git.yoctoproject.org/git/meta-virtualization @ 6c9b889224ce
cause do_fetch errors due to GitHub not accepting unauthenticated git
connections anymore and a branch name change. Fix this by adding bbappend
files to override the SRC_URI provided in the original recipes.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> Add bbappend for two recipes in meta-openembedded and meta-virtualization

meta-ledge-sw/recipes-ledge/images/files/init.cryptfs, meta-ledge-sw/recipes-security/optee/optee-client/create-tee-supplicant-env, meta-ledge-sw/recipes-security/optee/optee-client_%.bbappend
Two updates to `meta-ledge-sw/recipes-ledge/images/files/init.cryptfs`:
- Pass the ID of the eMMC to `tee-supplicant`
- A minor syntax fix
=> Add --rpmb-cid argument to tee-supplicant

meta-ledge-sw/recipes-ledge/images/files/init.cryptfs, meta-ledge-sw/recipes-security/optee/optee-client/create-tee-supplicant-env, meta-ledge-sw/recipes-security/optee/optee-client_%.bbappend
SD cards are wrongly detected as MMC by the scripts used to pass the
--rpmb-cid option to tee-supplicant. Use the 'type' entry in sysfs to
make sure we have indeed a (e)MMC and therefore a RPMB partition.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> optee: fix detection of RPMB device (--rpmb-cid)

meta-ledge-sw/recipes-ledge/images/files/init.cryptfs
Fix a typo in init.cryptfs (function name is rpmb_cid not rpmb-cid).
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> optee: init.cryptfs: one more RPMB fix

meta-ledge-sw/recipes-kernel/linux/linux-ledge_mainline.bb
Update kernel to 5.15.34. Fixes the following OP-TEE related kernel Oops
on RockPi4 boards (RPMB storage test):
```
[...]
reading 0
[ 1997.259928] ------------[ cut here ]------------
[ 1997.260389] kernel BUG at drivers/mmc/host/sdhci.c:774!
[ 1997.260877] Internal error: Oops - BUG: 0 [#1] PREEMPT SMP
[ 1997.261387] Modules linked in: bnep(E) overlay(E) btsdio(E) brcmfmac(E) snd_soc_hdmi_codec(E) dw_hdmi_i2s_audio(E) dw_hdmi_cec(E) rockchipdrm(E) hantro_vpu(CE) analogix_dp(E) brcmutil(E) dw_mipi_dsi(E) dw_hdmi(E) dwmac_rk(E) cec(E) v4l2_h264(E) drm_kms_helper(E) videobuf2_vmalloc(E) v4l2_mem2mem(E) stmmac_platform(E) hci_uart(E) videobuf2_dma_contig(E) stmmac(E) crct10dif_ce(E) ghash_ce(E) btqca(E) rockchip_saradc(E) phy_rockchip_pcie(E) videobuf2_memops(E) snd_soc_rockchip_i2s(E) …
```
=> linux-ledge_mainline.bb: use kernel 5.15.34

meta-ledge-sw/recipes-samples/images/ledge-minimal.bb, meta-ledge-sw/recipes-security/optee/optee-client/optee-udev.rules, meta-ledge-sw/recipes-security/optee/optee-client_%.bbappend
Due /dev/tee0 permissions, TEE applications currently have to run as root.
Introduce the teeclnt group so that application do not need full root
priviledges to access the TEE.
- the group is created by optee-client_%.bbappend
- ledge-minimal.bb is updated to add user 'ledge' to the 'teeclnt' group
for convenience (when OP-TEE is enabled)
- Permissions on device /dev/tee0 are set via udev rules, added to
optee-client_%.bbappend
Note that tee-supplicant is still run as root for simplicity and because
it seems there is not much security to gain from running it as a normal
user. It would still need CAP_SYS_RAWIO to access RPMB which is quite a
powerful capability already, and running as non-root introduces some
complexity (notably related to setting permissions on /dev/teepriv0 and
the …
=> optee-client: add teeclnt group for TEE client applications

meta-ledge-sw/recipes-security/optee/optee-test/0001-regression_6000.c-detect-available-storage-IDs-at-ru.patch, meta-ledge-sw/recipes-security/optee/optee-test_%.bbappend
Update xtest to detect which types of secure storage are supported by
the underlying OP-TEE at runtime. Fixes a couple of issues on RockPi 4
which has RPMB enabled (CFG_RPMB_FS=y) but REE FS disabled (CFG_REE_FS=n)
when optee-os is built:
1. xtest regression_6018 takes forever to complete because xtest wrongly
assumes that the default storage is REE FS and therefore it uses much
bigger data blocks than it should (32 KB vs 1 KB).
2. All the storage tests fail the REE FS part which should in fact not
be run.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> optee-test: add patch to detect storage (RPMB or not) dynamically

meta-ledge-sw/recipes-ledge/images/files/init.cryptfs, meta-ledge-sw/recipes-security/optee/optee-client_%.bbappend
A few patches addressing boot and shutdown issues I met on RockPi 4.
- The changes to `init.cryptfs` do what I expect at least but I have no idea about possible bad consequences so please review.
- The change to `tee-supplicant` shutdown is such that `systemctl stop tee-supplicant ; systemctl start tee-supplicant` will leave `tpm_ftpm_tee` unloaded. I don't know if it's an issue though.
=> Rockpi4 boot and halt fixes
